version: "3.3"

services:
  laravel:
    build: ./
    restart: always
    volumes:
      - "./:/var/www/html"
    depends_on:
      - sql_db
    env_file:
      - .env

  node:
    image: node:16
    working_dir: "/usr/src/app"
    volumes:
      - "./:/usr/src/app"
    entrypoint: bash -c "sleep infinity"
    command: bash -c "npm install && npm run dev" # use bash or ash

  sql_db:
    image: postgres:15
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: 14b8991c57d7b835f880acb316485a48e8792304eff78debe66d7e16032051d9
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8000:80
    volumes:
      - "./:/var/www/html"
      - "./logs/nginx:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - node
      - laravel
